# Generated by Django 4.0.6 on 2022-08-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digitalwallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Amount',
            new_name='amount',
        ),
    ]
